### ISSUE TITLE
Just wanted to say...this is awesome! Very useful examples

### ISSUE THREAD

**Issue by markcmiller86** [joaomlneto/cpds-heat#1]

**Comment by joaomlneto** [comment]
Thanks a lot!! :-)

Credits go to [José Ramón Herrero](http://personals.ac.upc.edu/jguitart/), [Jordi Guitart](http://personals.ac.upc.edu/jguitart/) and [Joaquim Gabarró](https://www.cs.upc.edu/~gabarro/) for the course!

Credits to my colleague [Fotios Papaodyssefs](https://www.linkedin.com/in/fotiospapaodyssefs/) for the teamwork :-)
